



/* 
 * CREACIÓN DE USUARIO SI TRABAJAS CON ORACLE CLOUD 
 *
 * Ejecuta este script conectado con el usuario ADMIN
 *
 */

-- Ejecutar este script conectado con el usuario ADMIN en Oracle Cloud

CREATE USER FULLSTACK_S4
IDENTIFIED BY "FullS4_202501."
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION, RESOURCE TO FULLSTACK_S4;

ALTER USER FULLSTACK_S4
DEFAULT ROLE RESOURCE;